; Listing generated by Microsoft (R) Optimizing Compiler Version 19.16.27025.1 

; Generated by VC++ for Common Language Runtime
.file "E:\Programming\repos\spse\GAL_PRG\calculator\calculator\calculator\x64\Debug\.NETFramework,Version=v4.6.1.AssemblyAttributes.cpp"
